CREATE TABLE IF NOT EXISTS TBL_TRAININGS
(
    COL_ID INT NOT NULL PRIMARY  KEY AUTO_INCREMENT,
    COL_TOPIC VARCHAR(255) NOT NULL,
    COL_LOCATION VARCHAR(255) NOT NULL,
    COL_INSTRUCTOR_NAME VARCHAR(255) NOT NULL
); -- ENGINE=INNODB;