logging:
  pattern:
# Ohne Datum/Uhrzeit, besser fuer Video-Demo
    console: "%magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    de.trion.trainingapp: info
  file:
    name: /tmp/training.log
training:
  default-location: Web


---
spring:
  config:
    activate:
      on-profile: dev
training:
  default-location: entwicklung-yaml

---
spring:
  config:
    activate:
      on-profile: test

training:
  default-location: test-location