logging:
  pattern:
# Ohne Datum/Uhrzeit, besser fuer Video-Demo
    console: "%magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  level:
    de.trion.trainingapp: info
#    org.apache.http: trace
#    org.springframework:
#      web.client.RestTemplate: trace
#      jdbc: trace
  file:
    name: /tmp/training.log
training:
  default-location: Web

spring:
  data:
    web:
      pageable:
        default-page-size: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#  datasource:
#    url: jdbc:mariadb://localhost/training
#    username: root
#    password: training

---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev-migration
  config:
    activate:
      on-profile: dev
training:
  default-location: entwicklung-yaml

---
spring:
  config:
    activate:
      on-profile: test

  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/dev-migration

training:
  default-location: test-location

#logging.level:
#  org.springframework.test:
#    context: debug